<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../IndustrialDataSim.Core/IndustrialDataSim.Core.csproj" />
    <ProjectReference Include="../IndustrialDataSim.Runtime/IndustrialDataSim.Runtime.csproj" />
  </ItemGroup>
</Project>
