<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/IndustrialDataSim.Runtime/IndustrialDataSim.Runtime.csproj" />
    <None Include="../../examples/constant-simulation.json" Link="examples/constant-simulation.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../examples/boolean-gate-simulation.json" Link="examples/boolean-gate-simulation.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
